### ISSUE TITLE
[5.0][Feature][Proposal] Operations to become classes instead of Traits

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1578]
Operation = some action the user can perform on the Model, that could include an interface (so route, controller method, etc) but also some operation on the entry (so something to call inside the CrudPanel object);

Example: **Create** operation. **Update** operation. **Delete** operation. **Reorder** operation.

One operation can consist of:
- one/more routes;
- those routes could go to one/multiple EntityCrudController methods (called actions);
- methods and properties on the CrudPanel object;
- form validation files, or other parameters;

What I propose is that we isolate each operation into its own class, so that the definition in ```EntityCrudController::setup()``` would change to something like this:

```php
class ProductCrudController extends CrudController
{
    public function setup()
    {
        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        $this->crud->setModel('App\Models\Test');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/test');
        $this->crud->setEntityNameStrings('test', 'tests');

        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        $createFields = [
            [ // Text
                'name' => 'title',
                'label' => "Title",
                'type' => 'text',
            ],
            [   // Textarea
                'name' => 'description',
                'label' => 'Description',
                'type' => 'textarea'
            ],
            [   // Address
                'name' => 'address',
                'label' => 'Address',
                'type' => 'address',
                // optional
                'store_as_json' => true
            ],
        ];

        $updateFields = $createFields;
        $updateFields[] = [
            [   // Textarea
                'name' => 'observations',
                'label' => 'Observations',
                'type' => 'textarea'
            ],
        ];

        $this->crud->enable(new CreateOperation($createFields));
        $this->crud->enable(new UpdateOperation($updateFields));
        $this->crud->enable(new DeleteOperation);
        $this->crud->enable(new PreviewOperation);
        $this->crud->enable(new NestOperation('title', 0));
    }
}
```

This ```enable()``` would:
- attach more methods to the current controller (specified inside the operation object);
- attach more methods/properties to the CrudPanel object (specified inside the operation object);

I think this could:
- make it easier to create reusable operations (create a class that extends Operation and enable it in the controller);
- make it clearer which fields are used where;
- make it easier to define stuff that's mandatory for an operation (because it's an object, configuration is passed as parameters and IDE autocomplete will help);
- make it more obvious which operations are enabled for each EntityCrudController;

**Comment by tabacitu** [comment]
We could further improve this by moving the configuration layer into its own object. So:

```php
class ProductCrudController extends CrudController
{
    public function setup()
    {
        $this->crud = new App\Library\Backpack\Setup\ProductCrudSetup;
    }
}

class ProductCrudSetup extends CrudSetup {

    public function setup()
    {
        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        $this->crud->setModel('App\Models\Test');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/test');
        $this->crud->setEntityNameStrings('test', 'tests');

        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        $createFields = [
            [ // Text
                'name' => 'title',
                'label' => "Title",
                'type' => 'text',
            ],
            [   // Textarea
                'name' => 'description',
                'label' => 'Description',
                'type' => 'textarea'
            ],
            [   // Address
                'name' => 'address',
                'label' => 'Address',
                'type' => 'address',
                // optional
                'store_as_json' => true
            ],
        ];

        $updateFields = $createFields;
        $updateFields[] = [
            [   // Textarea
                'name' => 'observations',
                'label' => 'Observations',
                'type' => 'textarea'
            ],
        ];

        $this->crud->enable(new CreateOperation($createFields));
        $this->crud->enable(new UpdateOperation($updateFields));
        $this->crud->enable(new DeleteOperation);
        $this->crud->enable(new PreviewOperation);
        $this->crud->enable(new NestOperation('title', 0));
    }
}
```

In addition to the benefits above, this would:
- make the controller slim, instead of fat;
- solve our layering problem (right now we use EntityCrudController mostly to edit the properties of a secondary object, CrudPanel);
- allow us to pass that configuration object to other classes; so we could then create a Matrix field type, because we can pass the ProductCrudSetup object and the Matrix field type will know which fields/columns to show, what validation you need on each action, etc;

The downside of moving the configuration to its own object is that you can no longer enable/disable/do stuff depending on the request, the action, etc... tough choice...

**Comment by tabacitu** [comment]
This is no longer needed thanks to https://github.com/Laravel-Backpack/CRUD/pull/1937

Yes, Operations are still traits. But these traits now include the routes too. So everything you want is in one file:
- the operations (controller methods)
- the routes
- the views that are used (inside the controller methods)

You can easily enable/disable/reuse operations just by using the trait or not.

Still think the configuration file might be a good idea. But let's talk about that in its own thread, here - https://github.com/Laravel-Backpack/CRUD/issues/1600

**Comment by tabacitu** [comment]
Eeeeh... might not have been a bad idea after all. This _would_ make it even cleaner to create new operations. And it would allow us to enforce operations look and behave a certain way. It could also clean up the CrudPanel object.

If each Operation is a class (not an array), it would make it easier to further drill down, and add settings for a particular Action of an Operation (ex, Create operation has ```create()``` and ```store()``` - you might want to add a setting for one of those, but not both).

In this case, maybe it'd make more sense to be something like:
```php
class CrudPanel {
    public $operations = [
        Operation, // create
        Operation, // update
        Operation, // list
    ];
}
``` 

Where:
```php
class CreateOperation extends Operation {
    use HasFields, HasSaveAction, HasSettings;

    public $actions = ['create', 'store'];

    protected function routes($name, $controller, $options) {
        Route::get($name.'/create', [
            'as' => 'crud.'.$name.'.create',
            'uses' => $controller.'@create',
        ]);

        Route::put($name.'/create', [
            'as' => 'crud.'.$name.'.store',
            'uses' => $controller.'@store',
        ]);
    }
    public function create() {}
    public function store() {}
}

class Operation implements OperationTemplate {
     use HasSettings;
}

trait HasSettings {
    public $settings = array();

    public function set($keyName, $keyValue, $optionalActionName)
    public function get($keyName, $optionalActionName);
}

interface OperationTemplate {
    public $actions = array();
    public $settings = array();
    protected function routes($name, $controller, $options);
}
```

Food for thought...

**Comment by tabacitu** [comment]
If we:
- setup the routes in the controller, for each operation (#1937)
- add the ability to add settings to each operation/action (#1941)
- clean up the CrudPanel object (#1942)
- reassign the ```CRUD``` alias to the CrudPanel;
- make Operations classes instead of arrays (like this issue proposes);
- move the getters and setters to operations (ex: ```HasFields``` trait is used by both Create and Update operations, ```HasColumns``` by both Show and List); 

The new syntax, in the end, could be something like:

```php
<?php

class ProductCrudController extends CrudController
{
    public function setup()
    {
        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        CRUD::setModel('App\Models\Test');
        CRUD::setRoute(config('backpack.base.route_prefix') . '/test');
        CRUD::setEntityNameStrings('test', 'tests');

        /*
        |--------------------------------------------------------------------------
        | OPERATIONS
        |--------------------------------------------------------------------------
        */
        CRUD::enable(new CreateOperation);
        CRUD::enable(new UpdateOperation);
        CRUD::enable(new DeleteOperation);
        CRUD::enable(new PreviewOperation);
        CRUD::enable(new NestOperation('title', 0));

        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
       
        // how to configure one operation
        CRUD::operation('list')->addColumns(['title', 'description']);
        CRUD::operation('create')->addFields([
            [ // Text
                'name' => 'title',
                'label' => "Title",
                'type' => 'text',
            ],
            [   // Textarea
                'name' => 'description',
                'label' => 'Description',
                'type' => 'textarea'
            ],
            [   // Address
                'name' => 'address',
                'label' => 'Address',
                'type' => 'address',
                // optional
                'store_as_json' => true
            ],
        ]);

        // how to configure multiple operations
        CRUD::operation(['create', 'update'])->addField([ // Text
            'name' => 'title',
            'label' => "Title",
            'type' => 'text',
        ]);
        CRUD::operations(['list', 'show'])->addColumn([ // Text
            'name' => 'title',
            'label' => "Title",
            'type' => 'text',
        ]);

        // how to configure ALL operations
        CRUD::allOperations()->addFields([
            [ // Text
                'name' => 'title',
                'label' => "Title",
                'type' => 'text',
            ],
            [   // Textarea
                'name' => 'description',
                'label' => 'Description',
                'type' => 'textarea'
            ],
            [   // Address
                'name' => 'address',
                'label' => 'Address',
                'type' => 'address',
                // optional
                'store_as_json' => true
            ],
        ]);
        CRUD::allOperations()->removeField('email');


        // we could also add a magic method, so that if a method is called on the 
        // CRUD object and it doesn't exist, it would be called on all operations
        // THAT WAY, we can (also) forget allOperations(), so this would work the same:
        CRUD::addField('text');
        CRUD::addColumn('name');
    }
}
```

Might be better than the current syntax. Might be worse. We'd obviously encourage configuring each operation individually, but there will be people configuring stuff for ALL operations.

**Comment by tabacitu** [comment]
I think from the list of to-dos above, the following are a MUST:
- [ ] setup the routes in the controller, for each operation (#1937)
- [ ] add the ability to add settings to each operation/action (#1941)
- [ ] clean up the CrudPanel object (#1942)
- [ ] reassign the CRUD alias to the CrudPanel (#1988)

And the following are a COULD:
- [ ] make Operations classes instead of traits (like this issue proposes);
- [ ] move the getters and setters to operations (ex: HasFields trait is used by both Create and Update operations, HasColumns by both Show and List);

Since there are separate issues for each of the MUSTs, and this issue is specifically about the COULDs, I'm going to reprioritize this as a COULD. Let's talk about it in 5.0.

**Comment by tabacitu** [comment]
It's been 3-4 months since the v4 launch and I have to say... Operations as Traits has worked GREAT. I see no reason to turn them into Classes at this time.

Let's table the discussion for now.
