### ISSUE TITLE
[Backlog] Known limitations/bugs/future features.

### ISSUE THREAD

**Issue by OwenMelbz** [Laravel-Backpack/CRUD#285]
I'm writing up a simple list which is effectively a consolidation of the issues, it can get a bit overwhelming with so many for a singular non-profit, so I'll be writing up this list and closing some tickets which we know about here to make it a little less busy!

**Known Issues**
- [x] [Table field type data is not compatible with laravel array/object/json casting](https://github.com/Laravel-Backpack/CRUD/issues/259)
- [x] [Ajax datatables with accessors/model functions](https://github.com/Laravel-Backpack/CRUD/issues/190) and [here](https://github.com/Laravel-Backpack/CRUD/issues/217)
- [x] [Cant selectively export results](https://github.com/Laravel-Backpack/CRUD/issues/169)
- [x] [Elfinder route difficulty](https://github.com/Laravel-Backpack/CRUD/issues/191)
- [x] [1-1 relationships not supported yet](https://github.com/Laravel-Backpack/CRUD/issues/250)

**Known Limitations**
- [x] [Select 2 can be updated](https://github.com/Laravel-Backpack/CRUD/issues/216)
- [x] [Custom doctrine column mappings](https://github.com/Laravel-Backpack/CRUD/issues/269)
- [x] [Bypass reserved keywords for queries](https://github.com/Laravel-Backpack/CRUD/issues/261)
- [x] [Responsive datatables](https://github.com/Laravel-Backpack/CRUD/issues/152)
- [ ] [Pagination position & back button](https://github.com/Laravel-Backpack/CRUD/issues/256)

**Future Features**
- [ ] [Scopes on select_multiple](https://github.com/Laravel-Backpack/CRUD/issues/285)
- [x] [Ability to re-order automatic fields](https://github.com/Laravel-Backpack/CRUD/issues/280)
- [x] [Ajax select2 fields](https://github.com/Laravel-Backpack/CRUD/issues/166)
- [ ] [Republishing views/lang files](https://github.com/Laravel-Backpack/CRUD/issues/140)
- [ ] [Custom entity level views](https://github.com/Laravel-Backpack/CRUD/issues/285) 
- [ ] [Adding CRUD entities from select field types](https://github.com/Laravel-Backpack/CRUD/issues/288)

**Pending PR**
- [ ] [Hooks for adjusting cruds after save/update](https://github.com/Laravel-Backpack/CRUD/issues/255)
- [x] [Inline error messages](https://github.com/Laravel-Backpack/CRUD/issues/71)

**Comment by eddilou** [comment]
Tell me, is the problem # 280 solved? Or in development?

**Comment by tabacitu** [comment]
@eddilou it was fixed and merged!

@OwenMelbz I'm going to close this issue, as all the bugs have been fixed. Only features are left, which I think should each have their own conversation.

Thank you for managing this whole thing.

Cheers!
