### ISSUE TITLE
[4.2][Bug][WIP] Not all fields work as subfields inside relationship

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4109]
Right now, we do NOT have a clear map:
- what field types works as `subfields` inside `repeatable`?
- what field types work as `subfields` inside `relationship`?
- is there any difference between the two?

And we should. We MUST. It's just a matter of time before somebody tries a combination we haven't - and they will get a horrible experience. **If we do not tell them "_X does not work as subfield_", they will expect _everything_ to work as subfields.** So we need to TEST EVERYTHING, KNOW what works and what doesn't and DOCUMENT what works and what doesn't. Then, one by one, we can make them work (if it's reasonable to do so). Here's my first attempt to test EVERYTHING.

## How did I test

I've submitted a PR to the demo with an extra interface we can use to test the stuff above. See PR // TODO

In that PR, I've added two new entities, `Hero` and `Story`:
- Hero `hasOne` Monster (there's a `hero_id` on `monsters` now)
- Story `hasMany` Hero (there's a `story_id` on `heroes`)

**Comment by tabacitu** [comment]
Now let's see which ones work and which ones don't... I'll update this table as I test...

### Can I use this field as a subfield?

| Field Type | Repeatable | 1-1 relationship | 1-n relationship | n-n relationship (pivot) |
| --- | ----------- | ----------- | ----------- | ----------- |
| address_algolia | ❓ |  ❓  |  ❓  | ❓  |
| address_google | ❓ |  ❓  |  ❓  | ❓  |
| browse | ❓ |  ❓  |  ❓  | ❓  |
| browse_multiple | ❓ |  ❓  |  ❓  | ❓  |
| base64_image | ❓ |  ❓  |  ❓  | ❓  |
| checkbox | ❓ |  ❓  |  ❓  | ❓  |
| checklist | ❓ |  ❓  |  ❓  | ❓  |
| checklist_dependency | ❓ |  ❓  |  ❓  | ❓  |
| ckeditor | ❓ |  ❓  |  ❓  | ❓  |
| color | ❓ |  ❓  |  ❓  | ❓  |
| color_picker | ❓ |  ❓  |  ❓  | ❓  |
| custom_html | ❓ |  ❓  |  ❓  | ❓  |
| date | ❓ |  ❓  |  ❓  | ❓  |
| date_picker | ❓ |  ❓  |  ❓  | ❓  |
| date_range | ❓ |  ❓  |  ❓  | ❓  |
| datetime | ❓ |  ❓  |  ❓  | ❓  |
| datetime_picker | ❓ |  ❓  |  ❓  | ❓  |
| easymde | ❓ |  ❓  |  ❓  | ❓  |
| email | ❓ |  ❓  |  ❓  | ❓  |
| enum | ❓ |  ❓  |  ❓  | ❓  |
| hidden | ❓ |  ❓  |  ❓  | ❓  |
| icon_picker | ❓ |  ❓  |  ❓  | ❓  |
| image | ❓ |  ❓  |  ❓  | ❓  |
| month | ❓ |  ❓  |  ❓  | ❓  |
| number | ❓ |  ❓  |  ❓  | ❓  |
| password | ❓ |  ❓  |  ❓  | ❓  |
| radio | ❓ |  ❓  |  ❓  | ❓  |
| range | ❓ |  ❓  |  ❓  | ❓  |
| relationship | ❓ |  ❓  |  ❓  | ❓  |
| repeatable | ❓ |  ❓  |  ❓  | ❓  |
| select (1-n relationship) | ❓ |  ❓  |  ❓  | ❓  |
| select_grouped | ❓ |  ❓  |  ❓  | ❓  |
| select2 (1-n relationship) | ❓ |  ❓  |  ❓  | ❓  |
| select_multiple (n-n relationship) | ❓ |  ❓  |  ❓  | ❓  |
| select2_multiple (n-n relationship) | ❓ |  ❓  |  ❓  | ❓  |
| select2_nested | ❓ |  ❓  |  ❓  | ❓  |
| select2_grouped | ❓ |  ❓  |  ❓  | ❓  |
| select_and_order | ❓ |  ❓  |  ❓  | ❓  |
| select_from_array | ❓ |  ❓  |  ❓  | ❓  |
| select2_from_array | ❓ |  ❓  |  ❓  | ❓  |
| select2_from_ajax | ❓ |  ❓  |  ❓  | ❓  |
| select2_from_ajax_multiple | ❓ |  ❓  |  ❓  | ❓  |
| summernote | ❓ |  ❓  |  ❓  | ❓  |
| table | ❓ |  ❓  |  ❓  | ❓  |
| text | ❓ |  ❓  |  ❓  | ❓  |
| textarea | ❓ |  ❓  |  ❓  | ❓  |
| time | ❓ |  ❓  |  ❓  | ❓  |
| tinymce | ❓ |  ❓  |  ❓  | ❓  |
| upload | ❓ |  ❓  |  ❓  | ❓  |
| upload_multiple | ❓ |  ❓  |  ❓  | ❓  |
| url | ❓ |  ❓  |  ❓  | ❓  |
| video | ❓ |  ❓  |  ❓  | ❓  |
| view | ❓ |  ❓  |  ❓  | ❓  |
| week | ❓ |  ❓  |  ❓  | ❓  |
| wysiwyg | ❓ |  ❓  |  ❓  | ❓  |

**Comment by tabacitu** [comment]
Priorities:
- [ ] all relationships working as subfields (fixes https://github.com/Laravel-Backpack/CRUD/issues/4108#issuecomment-1019474950 by merging https://github.com/Laravel-Backpack/CRUD/pull/4127)
- [ ] fake fields as subfields (checks off a few boxes at the bottom of https://github.com/Laravel-Backpack/CRUD/issues/4109#issuecomment-1019323850)
- [ ] subfields can be defined using the string syntax (checks off a few boxes at the bottom of https://github.com/Laravel-Backpack/CRUD/issues/4109#issuecomment-1019323850)

**Comment by tabacitu** [comment]
I'm very happy with the progress on this. I've opened issues for the few cases I think we should fix before launch. Other than that... I'm comfortable with moving this to the 4.2.x board 🎉 to make it a  "problem for future us".

**Comment by tabacitu** [comment]
Round-up. There are still a few things to be done here, to consider the issue _completely_ closed:
- [ ] https://github.com/Laravel-Backpack/CRUD/issues/4138
- [ ] https://github.com/Laravel-Backpack/CRUD/issues/4140
- [ ] https://github.com/Laravel-Backpack/CRUD/issues/4141
- [ ] create a place in the Demo where we use Monster as a pivot table (TODO for @tabacitu )
- [ ] test all fields in said place in demo (TODO for @tabacitu )

**Comment by kee0624** [comment]
Hi, I recently just updated my laravel backpack from 4.1 to 5, and try to add the nested repeatable under the repeatable, there is an issue here like I am not allowed to click on the nested "New Item" on the nested repeatable field, but if I create the post and edit it later, I am allowed to click on the "New Item" button and it shows the nested repeated field, is it a bug or intended? And I saw the above table it said that the repeatable are not allowed to use as a subfield, so I am confused here, it should not be working, but why it is working when I edit the post.

**Comment by pxpm** [comment]
Hello @kee0624 . It migth display on page, but surelly it's not working. 

Subfields inside subfields are not supported. Some will display, some will not display and throw errors. Use at will, **we do not recommend and we do not support them** (for now). 

thanks

**Comment by guleswine** [comment]
```
                [   // Checklist
                    'name'        => 'sources',
                    'label'       => "Источники",
                    'type'        => 'select2_from_array',
                    'options'     => Source::where('removed',false)->get()->pluck('name','id'),
                    'default'     => Source::where('removed',false)->get()->pluck('id')->toArray(),
                   // 'allows_null' => false,
                    'allows_multiple' => true,
                    'wrapper' => [
                        'class' => 'form-group col-md-3',
                    ],
                ],
```
![select_from_array](https://user-images.githubusercontent.com/23197378/169656485-3812fbdd-8b70-459a-8e27-c2468cc09da1.gif)

Hey guys, I noticed this strange behavior

**Comment by pxpm** [comment]
Hello @guleswine it's indeed strange but I guess that it might be some corner case while using default values or something like that. As far as I am aware select2_from_array was working properly as a subfield. 

If you remove the `default` does the problem still happen ? 

If so, please open a separate issue so we can have a look at and don't forget about it in the middle of this thread. 

Thanks
