### ISSUE TITLE
[Bug] checklist_dependency field is not working on v6

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#5143]
# Bug report
User CRUD not working on the v6 Demo
https://demo-v6.backpackforlaravel.com/admin/user/create

# Causer
`checklist_dependency` field is broken.(not working on v6)

# TODO

- [x] fix `checklist_dependency` field
- [ ] add an example to v6-demo monster: field/columns both are missing.
- [ ] add `checklist_dependency` column to docs

**Comment by pxpm** [comment]
@karandatwani92 probably it needs to update the docs, because before you would do: `name => [name1, name2]` and we removed the array syntax, so now you should do `name=> 'name1,name2'` and it will work the same as before.

**Comment by tabacitu** [comment]
Can confirm there was a problem. But it's not that `checklist_dependency` isn't working on v6, but 
- as Pedro said above that the name is now a comma-separated string, NOT an arry;
- our demo wasn't using [the v6 branch of PermissionManager](https://github.com/Laravel-Backpack/PermissionManager/pull/326) which has that fix; I've pushed a change now, we are using it;

@karandatwani92 you can check in the online demo - it's working now, where previously it was throwing a 500 error - https://demo-v6.backpackforlaravel.com/admin/user/create

**Comment by tabacitu** [comment]
Checklist dependency is... in a gray area... it was a mistake to have it inside CRUD, it should have been in PermissionManager alone... I think the main reason we don't have it in the demo Monster is that... it doesn't work inside repeatable. And it would be a pain to make it work there, for no benefit - nobody is using it, nobody has asked for it.

So for the time being, let's not do too much about checklist_dependency. Let's just add the column docs, if we have that column at all.
